### ISSUE TITLE
InvalidArgumentException

### ISSUE THREAD

**Issue by emileblume** [frankbuijze/defbu_authenticator#1]
After installing the extension (v1.0.2) via composer I get an error. (TYPO3 10.4.9 / PHP 7.3.3)

(1/1) #1460976566 InvalidArgumentException
[module-system_DefbuAuthenticatorTxDefbuauthenticator] The option "source" is required and must not be empty 

in //public/typo3/sysext/core/Classes/Imaging/IconProvider/SvgIconProvider.php line 49
     */
    protected function generateMarkup(Icon $icon, array $options)
    {
        if (empty($options['source'])) {
            throw new \InvalidArgumentException('[' . $icon->getIdentifier() . '] The option "source" is required and must not be empty', 1460976566);
        }

        $source = $options['source'];

**Comment by Patta** [comment]
I can confirm this issue with TYPO3 10.4.12 and PHP 7.4

https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/BackendModules/BackendModuleApi/Index.html#registering-new-modules
